const ROMAN_LITERALS: [char; 7] = ['I', 'V', 'X', 'L', 'C', 'D', 'M'];
const ARAB_MAP: [u16; 7] = [1, 5, 10, 50, 100, 500, 1000];
pub struct RomanNumber;

impl RomanNumber {
    pub fn is_valid(ch: char) -> bool {
        ROMAN_LITERALS.contains(&ch)
    }
    pub fn from_arab(arab: u16) -> Result<char, String> {
        let index = ARAB_MAP.iter().position(|&r| r == arab);
        if let Some(index) = index {
            Ok(ROMAN_LITERALS[index])
        } else {
            Err("This number has no roman equivalent.".into())
        }
    }
    pub fn to_arab(roman: char) -> Result<u16, String> {
        let index = ROMAN_LITERALS.iter().position(|&r| r == roman);
        if let Some(index) = index {
            Ok(ARAB_MAP[index])
        } else {
            Err("Invalid roman number.".into())
        }
    }
}

pub fn arab_to_roman(arab_number: u32) -> Result<String, String> {
    // split into number parts with modulus of closest smaller roman number
    // convert each part to roman
    // join them together
    

    // 46 (XLVI) -> [40, 6]
    // 473 (CDLXXIII) -> [400, 73] -> [400, 50, 23] -> [400, 50, 20, 3]
    //
    // 99 -> [50, 40, 9]
    //  90 - 50 = 40
    //  99 % 40 = 55
    // 99 -> [90, 9]
    //  90 - 10 = 90
    //  99 % 90 = 9

    let mut result = String::new();
    let mut remainder = arab_number;
        let mut i = ARAB_MAP.len();
        while i > 0{
            i -= 1;
            let arab = ARAB_MAP[i] as u32;
            let roman = ROMAN_LITERALS[i];

            let count = (remainder as f32 / arab as f32).floor() as usize;
            let rem = remainder % arab;
    
            remainder = rem;
             if count > 3 {
                result.push(roman);
                continue;
            }

            result.push_str(&roman.to_string().repeat(count));
            if rem == remainder {
                if i > 0 {
                    let prev_arab = ARAB_MAP[i-1];

                    let rem1 = remainder % (arab - prev_arab as u32);
                    let (rem, prev_arab) = if i > 1 {
                        let prev_prev_arab = ARAB_MAP[i-2];
                        let rem2 = remainder % (arab - prev_prev_arab as u32);

                        let mut r = (rem1, ROMAN_LITERALS[i-1]);
                        if rem2 < rem1 {
                            r = (rem2, ROMAN_LITERALS[i-2]);
                        }
                        r
                    }   else {
                        (rem1, ROMAN_LITERALS[i-1])
                    };

                    if rem != remainder {
                        result.push(prev_arab);
                        result.push(roman);
                        remainder = rem;
                    }
                }
                continue;
            }
        }

            
    println!("result for {}: {}", arab_number, result);
    Ok(result)
}

/// Converts Roman to Arab
pub fn roman_to_arab(roman_number: &str) -> Result<u32, String> {
    let chars: Vec<char> = roman_number.chars().collect();

    // XLIX
    let mut result = 0u32;

    //               (the number, occurance count)
    let mut prev_n = (0, 0);
    for ch in &chars {
        if !RomanNumber::is_valid(*ch) {
            return Err("Invalid input.".into());
        }
        let n = RomanNumber::to_arab(*ch)?;

        if n == prev_n.0 {
            prev_n.1 += 1;
            if prev_n.1 > 3 {
                return Err("Invalid input.".into());
            }
        } else {
            if n > prev_n.0 {
                if prev_n.1 > 1 {
                    return Err("Invalid input.".into());
                }
            }
            prev_n = (n, 1);
        }
    }
    let mut same_num_count = 0;
    let mut ch_idx = 0;
    while ch_idx < chars.len() {
        let ch = chars[ch_idx];
        let prev_ch = if ch_idx > 0 {
            Some(chars[ch_idx - 1])
        } else {
            None
        };
        let next_ch = chars.get(ch_idx + 1);

        let num = RomanNumber::to_arab(ch)?;
        if let Some(next_ch) = next_ch {
            let next_num = RomanNumber::to_arab(*next_ch)?;

            // the number should be substracted
            if next_num > num {
                let idx = ARAB_MAP.iter().position(|&n| n == num).unwrap(); // this cant fail

                // check if the number can be substracted (it is smaller by at most 2 roman steps)
                let mut possibilities = vec![];
                let next_n = ARAB_MAP.get(idx + 1).unwrap(); // this cant fail
                possibilities.push(*next_n);
                if let Some(next_n) = ARAB_MAP.get(idx + 2) {
                    possibilities.push(*next_n);
                }

                // fail if its not possible to substract
                if !possibilities.contains(&next_num) {
                    return Err("Invalid input.".into());
                }

                result += (next_num - num) as u32;
                ch_idx += 2;
                continue;
            }
        }

        if let Some(prev_ch) = prev_ch {
            let prev_num = RomanNumber::to_arab(prev_ch)?;
            // the number should be added
            if prev_num >= num {
                // check if the same number appeared more than 3 times in a row
                if prev_num == num {
                    same_num_count += 1;

                    // fail if it did
                    if same_num_count > 3 {
                        return Err("Invalid input.".into());
                    }
                } else {
                    // if the number is different, reset the counter
                    same_num_count = 1;
                }
            }
        }
        result += num as u32;
        ch_idx += 1;
    }

    Ok(result)
}

#[cfg(test)]
mod tests {
    use test_case::test_case;

    #[test_case("I", 1)]
    #[test_case("XXXIV", 34)]
    #[test_case("LXVII", 67)]
    #[test_case("II", 2)]
    #[test_case("XXXV", 35)]
    #[test_case("LXVIII", 68)]
    #[test_case("III", 3)]
    #[test_case("XXXVI", 36)]
    #[test_case("LXIX", 69)]
    #[test_case("IV", 4)]
    #[test_case("XXXVII", 37)]
    #[test_case("LXX", 70)]
    #[test_case("V", 5)]
    #[test_case("XXXVIII", 38)]
    #[test_case("LXXI", 71)]
    #[test_case("VI", 6)]
    #[test_case("XXXIX", 39)]
    #[test_case("LXXII", 72)]
    #[test_case("VII", 7)]
    #[test_case("XL", 40)]
    #[test_case("LXXIII", 73)]
    #[test_case("VIII", 8)]
    #[test_case("XLI", 41)]
    #[test_case("LXXIV", 74)]
    #[test_case("IX", 9)]
    #[test_case("XLII", 42)]
    #[test_case("LXXV", 75)]
    #[test_case("X", 10)]
    #[test_case("XLIII", 43)]
    #[test_case("LXXVI", 76)]
    #[test_case("XI", 11)]
    #[test_case("XLIV", 44)]
    #[test_case("LXXVII", 77)]
    #[test_case("XII", 12)]
    #[test_case("XLV", 45)]
    #[test_case("LXXVIII", 78)]
    #[test_case("XIII", 13)]
    #[test_case("XLVI", 46)]
    #[test_case("LXXIX", 79)]
    #[test_case("XIV", 14)]
    #[test_case("XLVII", 47)]
    #[test_case("LXXX", 80)]
    #[test_case("XV", 15)]
    #[test_case("XLVIII", 48)]
    #[test_case("LXXXI", 81)]
    #[test_case("XVI", 16)]
    #[test_case("XLIX", 49)]
    #[test_case("LXXXII", 82)]
    #[test_case("XVII", 17)]
    #[test_case("L", 50)]
    #[test_case("LXXXIII", 83)]
    #[test_case("XVIII", 18)]
    #[test_case("LI", 51)]
    #[test_case("LXXXIV", 84)]
    #[test_case("XIX", 19)]
    #[test_case("LII", 52)]
    #[test_case("LXXXV", 85)]
    #[test_case("XX", 20)]
    #[test_case("LIII", 53)]
    #[test_case("LXXXVI", 86)]
    #[test_case("XXI", 21)]
    #[test_case("LIV", 54)]
    #[test_case("LXXXVII", 87)]
    #[test_case("XXII", 22)]
    #[test_case("LV", 55)]
    #[test_case("LXXXVIII", 88)]
    #[test_case("XXIII", 23)]
    #[test_case("LVI", 56)]
    #[test_case("LXXXIX", 89)]
    #[test_case("XXIV", 24)]
    #[test_case("LVII", 57)]
    #[test_case("XC", 90)]
    #[test_case("XXV", 25)]
    #[test_case("LVIII", 58)]
    #[test_case("XCI", 91)]
    #[test_case("XXVI", 26)]
    #[test_case("LIX", 59)]
    #[test_case("XCII", 92)]
    #[test_case("XXVII", 27)]
    #[test_case("LX", 60)]
    #[test_case("XCIII", 93)]
    #[test_case("XXVIII", 28)]
    #[test_case("LXI", 61)]
    #[test_case("XCIV", 94)]
    #[test_case("XXIX", 29)]
    #[test_case("LXII", 62)]
    #[test_case("XCV", 95)]
    #[test_case("XXX", 30)]
    #[test_case("LXIII", 63)]
    #[test_case("XCVI", 96)]
    #[test_case("XXXI", 31)]
    #[test_case("LXIV", 64)]
    #[test_case("XCVII", 97)]
    #[test_case("XXXII", 32)]
    #[test_case("LXV", 65)]
    #[test_case("XCVIII", 98)]
    #[test_case("XXXIII", 33)]
    #[test_case("LXVI", 66)]
    #[test_case("XCIX", 99)]
    #[test_case("C", 100)]
    #[test_case("CI", 101)]
    #[test_case("CXXXIV", 134)]
    #[test_case("CLXVII", 167)]
    #[test_case("CII", 102)]
    #[test_case("CXXXV", 135)]
    #[test_case("CLXVIII", 168)]
    #[test_case("CIII", 103)]
    #[test_case("CXXXVI", 136)]
    #[test_case("CLXIX", 169)]
    #[test_case("CIV", 104)]
    #[test_case("CXXXVII", 137)]
    #[test_case("CLXX", 170)]
    #[test_case("CV", 105)]
    #[test_case("CXXXVIII", 138)]
    #[test_case("CLXXI", 171)]
    #[test_case("CVI", 106)]
    #[test_case("CXXXIX", 139)]
    #[test_case("CLXXII", 172)]
    #[test_case("CVII", 107)]
    #[test_case("CXL", 140)]
    #[test_case("CLXXIII", 173)]
    #[test_case("CVIII", 108)]
    #[test_case("CXLI", 141)]
    #[test_case("CIX", 109)]
    #[test_case("CXLII", 142)]
    #[test_case("CLXXV", 175)]
    #[test_case("CX", 110)]
    #[test_case("CXLIII", 143)]
    #[test_case("CLXXVI", 176)]
    #[test_case("CXI", 111)]
    #[test_case("CXLIV", 144)]
    #[test_case("CLXXVII", 177)]
    #[test_case("CXII", 112)]
    #[test_case("CXLV", 145)]
    #[test_case("CLXXVIII", 178)]
    #[test_case("CXIII", 113)]
    #[test_case("CXLVI", 146)]
    #[test_case("CLXXIX", 179)]
    #[test_case("CXIV", 114)]
    #[test_case("CXLVII", 147)]
    #[test_case("CLXXX", 180)]
    #[test_case("CXV", 115)]
    #[test_case("CXLVIII", 148)]
    #[test_case("CLXXXI", 181)]
    #[test_case("CXVI", 116)]
    #[test_case("CLXXXII", 182)]
    #[test_case("CXVII", 117)]
    #[test_case("CL", 150)]
    #[test_case("CLXXXIII", 183)]
    #[test_case("CXVIII", 118)]
    #[test_case("CLI", 151)]
    #[test_case("CLXXXIV", 184)]
    #[test_case("CXIX", 119)]
    #[test_case("CLII", 152)]
    #[test_case("CLXXXV", 185)]
    #[test_case("CXX", 120)]
    #[test_case("CLIII", 153)]
    #[test_case("CLXXXVI", 186)]
    #[test_case("CXXI", 121)]
    #[test_case("CLIV", 154)]
    #[test_case("CLXXXVII", 187)]
    #[test_case("CXXII", 122)]
    #[test_case("CLV", 155)]
    #[test_case("CLXXXVIII", 188)]
    #[test_case("CXXIII", 123)]
    #[test_case("CLVI", 156)]
    #[test_case("CLXXXIX", 189)]
    #[test_case("CLVII", 157)]
    #[test_case("CXC", 190)]
    #[test_case("CXXV", 125)]
    #[test_case("CLVIII", 158)]
    #[test_case("CXCI", 191)]
    #[test_case("CXXVI", 126)]
    #[test_case("CLIX", 159)]
    #[test_case("CXCII", 192)]
    #[test_case("CXXVII", 127)]
    #[test_case("CLX", 160)]
    #[test_case("CXCIII", 193)]
    #[test_case("CXXVIII", 128)]
    #[test_case("CLXI", 161)]
    #[test_case("CXCIV", 194)]
    #[test_case("CXXIX", 129)]
    #[test_case("CLXII", 162)]
    #[test_case("CXCV", 195)]
    #[test_case("CXXX", 130)]
    #[test_case("CLXIII", 163)]
    #[test_case("CXCVI", 196)]
    #[test_case("CXXXI", 131)]
    #[test_case("CLXIV", 164)]
    #[test_case("CXCVII", 197)]
    #[test_case("CXXXII", 132)]
    #[test_case("CLXV", 165)]
    #[test_case("CXCVIII", 198)]
    #[test_case("CXXXIII", 133)]
    #[test_case("CLXVI", 166)]
    #[test_case("CC", 200)]
    #[test_case("CCI", 201)]
    #[test_case("CCXXXIV", 234)]
    #[test_case("CCLXVII", 267)]
    #[test_case("CCII", 202)]
    #[test_case("CCXXXV", 235)]
    #[test_case("CCLXVIII", 268)]
    #[test_case("CCIII", 203)]
    #[test_case("CCXXXVI", 236)]
    #[test_case("CCLXIX", 269)]
    #[test_case("CCIV", 204)]
    #[test_case("CCXXXVII", 237)]
    #[test_case("CCLXX", 270)]
    #[test_case("CCV", 205)]
    #[test_case("CCXXXVIII", 238)]
    #[test_case("CCLXXI", 271)]
    #[test_case("CCVI", 206)]
    #[test_case("CCXXXIX", 239)]
    #[test_case("CCLXXII", 272)]
    #[test_case("CCVII", 207)]
    #[test_case("CCXL", 240)]
    #[test_case("CCLXXIII", 273)]
    #[test_case("CCVIII", 208)]
    #[test_case("CCXLI", 241)]
    #[test_case("CCLXXIV", 274)]
    #[test_case("CCIX", 209)]
    #[test_case("CCXLII", 242)]
    #[test_case("CCLXXV", 275)]
    #[test_case("CCX", 210)]
    #[test_case("CCXLIII", 243)]
    #[test_case("CCLXXVI", 276)]
    #[test_case("CCXI", 211)]
    #[test_case("CCXLIV", 244)]
    #[test_case("CCLXXVII", 277)]
    #[test_case("CCXII", 212)]
    #[test_case("CCXLV", 245)]
    #[test_case("CCLXXVIII", 278)]
    #[test_case("CCXIII", 213)]
    #[test_case("CCXLVI", 246)]
    #[test_case("CCLXXIX", 279)]
    #[test_case("CCXIV", 214)]
    #[test_case("CCXLVII", 247)]
    #[test_case("CCLXXX", 280)]
    #[test_case("CCXV", 215)]
    #[test_case("CCXLVIII", 248)]
    #[test_case("CCLXXXI", 281)]
    #[test_case("CCXVI", 216)]
    #[test_case("CCXLIX", 249)]
    #[test_case("CCLXXXII", 282)]
    #[test_case("CCXVII", 217)]
    #[test_case("CCL", 250)]
    #[test_case("CCLXXXIII", 283)]
    #[test_case("CCXVIII", 218)]
    #[test_case("CCLI", 251)]
    #[test_case("CCLXXXIV", 284)]
    #[test_case("CCXIX", 219)]
    #[test_case("CCLII", 252)]
    #[test_case("CCLXXXV", 285)]
    #[test_case("CCXX", 220)]
    #[test_case("CCLIII", 253)]
    #[test_case("CCLXXXVI", 286)]
    #[test_case("CCXXI", 221)]
    #[test_case("CCLIV", 254)]
    #[test_case("CCLXXXVII", 287)]
    #[test_case("CCXXII", 222)]
    #[test_case("CCLV", 255)]
    #[test_case("CCLXXXVIII", 288)]
    #[test_case("CCXXIII", 223)]
    #[test_case("CCLVI", 256)]
    #[test_case("CCLXXXIX", 289)]
    #[test_case("CCXXIV", 224)]
    #[test_case("CCLVII", 257)]
    #[test_case("CCXC", 290)]
    #[test_case("CCXXV", 225)]
    #[test_case("CCLVIII", 258)]
    #[test_case("CCXCI", 291)]
    #[test_case("CCXXVI", 226)]
    #[test_case("CCLIX", 259)]
    #[test_case("CCXCII", 292)]
    #[test_case("CCXXVII", 227)]
    #[test_case("CCLX", 260)]
    #[test_case("CCXCIII", 293)]
    #[test_case("CCXXVIII", 228)]
    #[test_case("CCLXI", 261)]
    #[test_case("CCXCIV", 294)]
    #[test_case("CCXXIX", 229)]
    #[test_case("CCLXII", 262)]
    #[test_case("CCXCV", 295)]
    #[test_case("CCXXX", 230)]
    #[test_case("CCLXIII", 263)]
    #[test_case("CCXCVI", 296)]
    #[test_case("CCXXXI", 231)]
    #[test_case("CCLXIV", 264)]
    #[test_case("CCXCVII", 297)]
    #[test_case("CCXXXII", 232)]
    #[test_case("CCLXV", 265)]
    #[test_case("CCXCVIII", 298)]
    #[test_case("CCXXXIII", 233)]
    #[test_case("CCLXVI", 266)]
    #[test_case("CCXCIX", 299)]
    #[test_case("CCC", 300)]
    #[test_case("CCCI", 301)]
    #[test_case("CCCXXXIV", 334)]
    #[test_case("CCCLXVII", 367)]
    #[test_case("CCCII", 302)]
    #[test_case("CCCXXXV", 335)]
    #[test_case("CCCLXVIII", 368)]
    #[test_case("CCCIII", 303)]
    #[test_case("CCCXXXVI", 336)]
    #[test_case("CCCLXIX", 369)]
    #[test_case("CCCIV", 304)]
    #[test_case("CCCXXXVII", 337)]
    #[test_case("CCCLXX", 370)]
    #[test_case("CCCV", 305)]
    #[test_case("CCCXXXVIII", 338)]
    #[test_case("CCCLXXI", 371)]
    #[test_case("CCCVI", 306)]
    #[test_case("CCCXXXIX", 339)]
    #[test_case("CCCLXXII", 372)]
    #[test_case("CCCVII", 307)]
    #[test_case("CCCXL", 340)]
    #[test_case("CCCLXXIII", 373)]
    #[test_case("CCCVIII", 308)]
    #[test_case("CCCXLI", 341)]
    #[test_case("CCCLXXIV", 374)]
    #[test_case("CCCIX", 309)]
    #[test_case("CCCXLII", 342)]
    #[test_case("CCCLXXV", 375)]
    #[test_case("CCCX", 310)]
    #[test_case("CCCXLIII", 343)]
    #[test_case("CCCLXXVI", 376)]
    #[test_case("CCCXI", 311)]
    #[test_case("CCCXLIV", 344)]
    #[test_case("CCCLXXVII", 377)]
    #[test_case("CCCXII", 312)]
    #[test_case("CCCXLV", 345)]
    #[test_case("CCCLXXVIII", 378)]
    #[test_case("CCCXIII", 313)]
    #[test_case("CCCXLVI", 346)]
    #[test_case("CCCLXXIX", 379)]
    #[test_case("CCCXIV", 314)]
    #[test_case("CCCXLVII", 347)]
    #[test_case("CCCLXXX", 380)]
    #[test_case("CCCXV", 315)]
    #[test_case("CCCXLVIII", 348)]
    #[test_case("CCCLXXXI", 381)]
    #[test_case("CCCXVI", 316)]
    #[test_case("CCCXLIX", 349)]
    #[test_case("CCCLXXXII", 382)]
    #[test_case("CCCXVII", 317)]
    #[test_case("CCCL", 350)]
    #[test_case("CCCLXXXIII", 383)]
    #[test_case("CCCXVIII", 318)]
    #[test_case("CCCLI", 351)]
    #[test_case("CCCLXXXIV", 384)]
    #[test_case("CCCXIX", 319)]
    #[test_case("CCCLII", 352)]
    #[test_case("CCCLXXXV", 385)]
    #[test_case("CCCXX", 320)]
    #[test_case("CCCLIII", 353)]
    #[test_case("CCCLXXXVI", 386)]
    #[test_case("CCCXXI", 321)]
    #[test_case("CCCLIV", 354)]
    #[test_case("CCCLXXXVII", 387)]
    #[test_case("CCCXXII", 322)]
    #[test_case("CCCLV", 355)]
    #[test_case("CCCLXXXVIII", 388)]
    #[test_case("CCCXXIII", 323)]
    #[test_case("CCCLVI", 356)]
    #[test_case("CCCLXXXIX", 389)]
    #[test_case("CCCXXIV", 324)]
    #[test_case("CCCLVII", 357)]
    #[test_case("CCCXC", 390)]
    #[test_case("CCCXXV", 325)]
    #[test_case("CCCLVIII", 358)]
    #[test_case("CCCXCI", 391)]
    #[test_case("CCCXXVI", 326)]
    #[test_case("CCCLIX", 359)]
    #[test_case("CCCXCII", 392)]
    #[test_case("CCCXXVII", 327)]
    #[test_case("CCCLX", 360)]
    #[test_case("CCCXCIII", 393)]
    #[test_case("CCCXXVIII", 328)]
    #[test_case("CCCLXI", 361)]
    #[test_case("CCCXCIV", 394)]
    #[test_case("CCCXXIX", 329)]
    #[test_case("CCCLXII", 362)]
    #[test_case("CCCXCV", 395)]
    #[test_case("CCCXXX", 330)]
    #[test_case("CCCLXIII", 363)]
    #[test_case("CCCXCVI", 396)]
    #[test_case("CCCXXXI", 331)]
    #[test_case("CCCLXIV", 364)]
    #[test_case("CCCXCVII", 397)]
    #[test_case("CCCXXXII", 332)]
    #[test_case("CCCLXV", 365)]
    #[test_case("CCCXCVIII", 398)]
    #[test_case("CCCXXXIII", 333)]
    #[test_case("CCCLXVI", 366)]
    #[test_case("CCCXCIX", 399)]
    #[test_case("CD", 400)]
    #[test_case("CDI", 401)]
    #[test_case("CDXXXIV", 434)]
    #[test_case("CDLXVII", 467)]
    #[test_case("CDII", 402)]
    #[test_case("CDXXXV", 435)]
    #[test_case("CDLXVIII", 468)]
    #[test_case("CDIII", 403)]
    #[test_case("CDXXXVI", 436)]
    #[test_case("CDLXIX", 469)]
    #[test_case("CDIV", 404)]
    #[test_case("CDXXXVII", 437)]
    #[test_case("CDLXX", 470)]
    #[test_case("CDV", 405)]
    #[test_case("CDXXXVIII", 438)]
    #[test_case("CDLXXI", 471)]
    #[test_case("CDVI", 406)]
    #[test_case("CDXXXIX", 439)]
    #[test_case("CDLXXII", 472)]
    #[test_case("CDVII", 407)]
    #[test_case("CDXL", 440)]
    #[test_case("CDLXXIII", 473)]
    #[test_case("CDVIII", 408)]
    #[test_case("CDXLI", 441)]
    #[test_case("CDLXXIV", 474)]
    #[test_case("CDIX", 409)]
    #[test_case("CDXLII", 442)]
    #[test_case("CDLXXV", 475)]
    #[test_case("CDX", 410)]
    #[test_case("CDXLIII", 443)]
    #[test_case("CDLXXVI", 476)]
    #[test_case("CDXI", 411)]
    #[test_case("CDXLIV", 444)]
    #[test_case("CDLXXVII", 477)]
    #[test_case("CDXII", 412)]
    #[test_case("CDXLV", 445)]
    #[test_case("CDLXXVIII", 478)]
    #[test_case("CDXIII", 413)]
    #[test_case("CDXLVI", 446)]
    #[test_case("CDLXXIX", 479)]
    #[test_case("CDXIV", 414)]
    #[test_case("CDXLVII", 447)]
    #[test_case("CDLXXX", 480)]
    #[test_case("CDXV", 415)]
    #[test_case("CDXLVIII", 448)]
    #[test_case("CDLXXXI", 481)]
    #[test_case("CDXVI", 416)]
    #[test_case("CDXLIX", 449)]
    #[test_case("CDLXXXII", 482)]
    #[test_case("CDXVII", 417)]
    #[test_case("CDL", 450)]
    #[test_case("CDLXXXIII", 483)]
    #[test_case("CDXVIII", 418)]
    #[test_case("CDLI", 451)]
    #[test_case("CDLXXXIV", 484)]
    #[test_case("CDXIX", 419)]
    #[test_case("CDLII", 452)]
    #[test_case("CDLXXXV", 485)]
    #[test_case("CDXX", 420)]
    #[test_case("CDLIII", 453)]
    #[test_case("CDLXXXVI", 486)]
    #[test_case("CDXXI", 421)]
    #[test_case("CDLIV", 454)]
    #[test_case("CDLXXXVII", 487)]
    #[test_case("CDXXII", 422)]
    #[test_case("CDLV", 455)]
    #[test_case("CDLXXXVIII", 488)]
    #[test_case("CDXXIII", 423)]
    #[test_case("CDLVI", 456)]
    #[test_case("CDLXXXIX", 489)]
    #[test_case("CDXXIV", 424)]
    #[test_case("CDLVII", 457)]
    #[test_case("CDXC", 490)]
    #[test_case("CDXXV", 425)]
    #[test_case("CDLVIII", 458)]
    #[test_case("CDXCI", 491)]
    #[test_case("CDXXVI", 426)]
    #[test_case("CDLIX", 459)]
    #[test_case("CDXCII", 492)]
    #[test_case("CDXXVII", 427)]
    #[test_case("CDLX", 460)]
    #[test_case("CDXCIII", 493)]
    #[test_case("CDXXVIII", 428)]
    #[test_case("CDLXI", 461)]
    #[test_case("CDXCIV", 494)]
    #[test_case("CDXXIX", 429)]
    #[test_case("CDLXII", 462)]
    #[test_case("CDXCV", 495)]
    #[test_case("CDXXX", 430)]
    #[test_case("CDLXIII", 463)]
    #[test_case("CDXCVI", 496)]
    #[test_case("CDXXXI", 431)]
    #[test_case("CDLXIV", 464)]
    #[test_case("CDXCVII", 497)]
    #[test_case("CDXXXII", 432)]
    #[test_case("CDLXV", 465)]
    #[test_case("CDXCVIII", 498)]
    #[test_case("CDXXXIII", 433)]
    #[test_case("CDLXVI", 466)]
    #[test_case("CDXCIX", 499)]
    #[test_case("D", 500)]
    #[test_case("DI", 501)]
    #[test_case("DXXXIV", 534)]
    #[test_case("DLXVII", 567)]
    #[test_case("DII", 502)]
    #[test_case("DXXXV", 535)]
    #[test_case("DLXVIII", 568)]
    #[test_case("DIII", 503)]
    #[test_case("DXXXVI", 536)]
    #[test_case("DLXIX", 569)]
    #[test_case("DIV", 504)]
    #[test_case("DXXXVII", 537)]
    #[test_case("DLXX", 570)]
    #[test_case("DV", 505)]
    #[test_case("DXXXVIII", 538)]
    #[test_case("DLXXI", 571)]
    #[test_case("DVI", 506)]
    #[test_case("DXXXIX", 539)]
    #[test_case("DLXXII", 572)]
    #[test_case("DVII", 507)]
    #[test_case("DXL", 540)]
    #[test_case("DLXXIII", 573)]
    #[test_case("DVIII", 508)]
    #[test_case("DXLI", 541)]
    #[test_case("DLXXIV", 574)]
    #[test_case("DIX", 509)]
    #[test_case("DXLII", 542)]
    #[test_case("DLXXV", 575)]
    #[test_case("DX", 510)]
    #[test_case("DXLIII", 543)]
    #[test_case("DLXXVI", 576)]
    #[test_case("DXI", 511)]
    #[test_case("DXLIV", 544)]
    #[test_case("DLXXVII", 577)]
    #[test_case("DXII", 512)]
    #[test_case("DXLV", 545)]
    #[test_case("DLXXVIII", 578)]
    #[test_case("DXIII", 513)]
    #[test_case("DXLVI", 546)]
    #[test_case("DLXXIX", 579)]
    #[test_case("DXIV", 514)]
    #[test_case("DXLVII", 547)]
    #[test_case("DLXXX", 580)]
    #[test_case("DXV", 515)]
    #[test_case("DXLVIII", 548)]
    #[test_case("DLXXXI", 581)]
    #[test_case("DXVI", 516)]
    #[test_case("DXLIX", 549)]
    #[test_case("DLXXXII", 582)]
    #[test_case("DXVII", 517)]
    #[test_case("DL", 550)]
    #[test_case("DLXXXIII", 583)]
    #[test_case("DXVIII", 518)]
    #[test_case("DLI", 551)]
    #[test_case("DLXXXIV", 584)]
    #[test_case("DXIX", 519)]
    #[test_case("DLII", 552)]
    #[test_case("DLXXXV", 585)]
    #[test_case("DXX", 520)]
    #[test_case("DLIII", 553)]
    #[test_case("DLXXXVI", 586)]
    #[test_case("DXXI", 521)]
    #[test_case("DLIV", 554)]
    #[test_case("DLXXXVII", 587)]
    #[test_case("DXXII", 522)]
    #[test_case("DLV", 555)]
    #[test_case("DLXXXVIII", 588)]
    #[test_case("DXXIII", 523)]
    #[test_case("DLVI", 556)]
    #[test_case("DLXXXIX", 589)]
    #[test_case("DXXIV", 524)]
    #[test_case("DLVII", 557)]
    #[test_case("DXC", 590)]
    #[test_case("DXXV", 525)]
    #[test_case("DLVIII", 558)]
    #[test_case("DXCI", 591)]
    #[test_case("DXXVI", 526)]
    #[test_case("DLIX", 559)]
    #[test_case("DXCII", 592)]
    #[test_case("DXXVII", 527)]
    #[test_case("DLX", 560)]
    #[test_case("DXCIII", 593)]
    #[test_case("DXXVIII", 528)]
    #[test_case("DLXI", 561)]
    #[test_case("DXCIV", 594)]
    #[test_case("DXXIX", 529)]
    #[test_case("DLXII", 562)]
    #[test_case("DXCV", 595)]
    #[test_case("DXXX", 530)]
    #[test_case("DLXIII", 563)]
    #[test_case("DXCVI", 596)]
    #[test_case("DXXXI", 531)]
    #[test_case("DLXIV", 564)]
    #[test_case("DXCVII", 597)]
    #[test_case("DXXXII", 532)]
    #[test_case("DLXV", 565)]
    #[test_case("DXCVIII", 598)]
    #[test_case("DXXXIII", 533)]
    #[test_case("DLXVI", 566)]
    #[test_case("DXCIX", 599)]
    #[test_case("DC", 600)]
    #[test_case("DCI", 601)]
    #[test_case("DCXXXIV", 634)]
    #[test_case("DCLXVII", 667)]
    #[test_case("DCII", 602)]
    #[test_case("DCXXXV", 635)]
    #[test_case("DCLXVIII", 668)]
    #[test_case("DCIII", 603)]
    #[test_case("DCXXXVI", 636)]
    #[test_case("DCLXIX", 669)]
    #[test_case("DCIV", 604)]
    #[test_case("DCXXXVII", 637)]
    #[test_case("DCLXX", 670)]
    #[test_case("DCV", 605)]
    #[test_case("DCXXXVIII", 638)]
    #[test_case("DCLXXI", 671)]
    #[test_case("DCVI", 606)]
    #[test_case("DCXXXIX", 639)]
    #[test_case("DCLXXII", 672)]
    #[test_case("DCVII", 607)]
    #[test_case("DCXL", 640)]
    #[test_case("DCLXXIII", 673)]
    #[test_case("DCVIII", 608)]
    #[test_case("DCXLI", 641)]
    #[test_case("DCLXXIV", 674)]
    #[test_case("DCIX", 609)]
    #[test_case("DCXLII", 642)]
    #[test_case("DCLXXV", 675)]
    #[test_case("DCX", 610)]
    #[test_case("DCXLIII", 643)]
    #[test_case("DCLXXVI", 676)]
    #[test_case("DCXI", 611)]
    #[test_case("DCXLIV", 644)]
    #[test_case("DCLXXVII", 677)]
    #[test_case("DCXII", 612)]
    #[test_case("DCXLV", 645)]
    #[test_case("DCLXXVIII", 678)]
    #[test_case("DCXIII", 613)]
    #[test_case("DCXLVI", 646)]
    #[test_case("DCLXXIX", 679)]
    #[test_case("DCXIV", 614)]
    #[test_case("DCXLVII", 647)]
    #[test_case("DCLXXX", 680)]
    #[test_case("DCXV", 615)]
    #[test_case("DCXLVIII", 648)]
    #[test_case("DCLXXXI", 681)]
    #[test_case("DCXVI", 616)]
    #[test_case("DCXLIX", 649)]
    #[test_case("DCLXXXII", 682)]
    #[test_case("DCXVII", 617)]
    #[test_case("DCL", 650)]
    #[test_case("DCLXXXIII", 683)]
    #[test_case("DCXVIII", 618)]
    #[test_case("DCLI", 651)]
    #[test_case("DCLXXXIV", 684)]
    #[test_case("DCXIX", 619)]
    #[test_case("DCLII", 652)]
    #[test_case("DCLXXXV", 685)]
    #[test_case("DCXX", 620)]
    #[test_case("DCLIII", 653)]
    #[test_case("DCLXXXVI", 686)]
    #[test_case("DCXXI", 621)]
    #[test_case("DCLIV", 654)]
    #[test_case("DCLXXXVII", 687)]
    #[test_case("DCXXII", 622)]
    #[test_case("DCLV", 655)]
    #[test_case("DCLXXXVIII", 688)]
    #[test_case("DCXXIII", 623)]
    #[test_case("DCLVI", 656)]
    #[test_case("DCLXXXIX", 689)]
    #[test_case("DCXXIV", 624)]
    #[test_case("DCLVII", 657)]
    #[test_case("DCXC", 690)]
    #[test_case("DCXXV", 625)]
    #[test_case("DCLVIII", 658)]
    #[test_case("DCXCI", 691)]
    #[test_case("DCXXVI", 626)]
    #[test_case("DCLIX", 659)]
    #[test_case("DCXCII", 692)]
    #[test_case("DCXXVII", 627)]
    #[test_case("DCLX", 660)]
    #[test_case("DCXCIII", 693)]
    #[test_case("DCXXVIII", 628)]
    #[test_case("DCLXI", 661)]
    #[test_case("DCXCIV", 694)]
    #[test_case("DCXXIX", 629)]
    #[test_case("DCLXII", 662)]
    #[test_case("DCXCV", 695)]
    #[test_case("DCXXX", 630)]
    #[test_case("DCLXIII", 663)]
    #[test_case("DCXCVI", 696)]
    #[test_case("DCXXXI", 631)]
    #[test_case("DCLXIV", 664)]
    #[test_case("DCXCVII", 697)]
    #[test_case("DCXXXII", 632)]
    #[test_case("DCLXV", 665)]
    #[test_case("DCXCVIII", 698)]
    #[test_case("DCXXXIII", 633)]
    #[test_case("DCLXVI", 666)]
    #[test_case("DCXCIX", 699)]
    #[test_case("DCC", 700)]
    #[test_case("DCCI", 701)]
    #[test_case("DCCXXXIV", 734)]
    #[test_case("DCCLXVII", 767)]
    #[test_case("DCCII", 702)]
    #[test_case("DCCXXXV", 735)]
    #[test_case("DCCLXVIII", 768)]
    #[test_case("DCCIII", 703)]
    #[test_case("DCCXXXVI", 736)]
    #[test_case("DCCLXIX", 769)]
    #[test_case("DCCIV", 704)]
    #[test_case("DCCXXXVII", 737)]
    #[test_case("DCCLXX", 770)]
    #[test_case("DCCV", 705)]
    #[test_case("DCCXXXVIII", 738)]
    #[test_case("DCCLXXI", 771)]
    #[test_case("DCCVI", 706)]
    #[test_case("DCCXXXIX", 739)]
    #[test_case("DCCLXXII", 772)]
    #[test_case("DCCVII", 707)]
    #[test_case("DCCXL", 740)]
    #[test_case("DCCLXXIII", 773)]
    #[test_case("DCCVIII", 708)]
    #[test_case("DCCXLI", 741)]
    #[test_case("DCCLXXIV", 774)]
    #[test_case("DCCIX", 709)]
    #[test_case("DCCXLII", 742)]
    #[test_case("DCCLXXV", 775)]
    #[test_case("DCCX", 710)]
    #[test_case("DCCXLIII", 743)]
    #[test_case("DCCLXXVI", 776)]
    #[test_case("DCCXI", 711)]
    #[test_case("DCCXLIV", 744)]
    #[test_case("DCCLXXVII", 777)]
    #[test_case("DCCXII", 712)]
    #[test_case("DCCXLV", 745)]
    #[test_case("DCCLXXVIII", 778)]
    #[test_case("DCCXIII", 713)]
    #[test_case("DCCXLVI", 746)]
    #[test_case("DCCLXXIX", 779)]
    #[test_case("DCCXIV", 714)]
    #[test_case("DCCXLVII", 747)]
    #[test_case("DCCLXXX", 780)]
    #[test_case("DCCXV", 715)]
    #[test_case("DCCXLVIII", 748)]
    #[test_case("DCCLXXXI", 781)]
    #[test_case("DCCXVI", 716)]
    #[test_case("DCCXLIX", 749)]
    #[test_case("DCCLXXXII", 782)]
    #[test_case("DCCXVII", 717)]
    #[test_case("DCCL", 750)]
    #[test_case("DCCLXXXIII", 783)]
    #[test_case("DCCXVIII", 718)]
    #[test_case("DCCLI", 751)]
    #[test_case("DCCLXXXIV", 784)]
    #[test_case("DCCXIX", 719)]
    #[test_case("DCCLII", 752)]
    #[test_case("DCCLXXXV", 785)]
    #[test_case("DCCXX", 720)]
    #[test_case("DCCLIII", 753)]
    #[test_case("DCCLXXXVI", 786)]
    #[test_case("DCCXXI", 721)]
    #[test_case("DCCLIV", 754)]
    #[test_case("DCCLXXXVII", 787)]
    #[test_case("DCCXXII", 722)]
    #[test_case("DCCLV", 755)]
    #[test_case("DCCLXXXVIII", 788)]
    #[test_case("DCCXXIII", 723)]
    #[test_case("DCCLVI", 756)]
    #[test_case("DCCLXXXIX", 789)]
    #[test_case("DCCXXIV", 724)]
    #[test_case("DCCLVII", 757)]
    #[test_case("DCCXC", 790)]
    #[test_case("DCCXXV", 725)]
    #[test_case("DCCLVIII", 758)]
    #[test_case("DCCXCI", 791)]
    #[test_case("DCCXXVI", 726)]
    #[test_case("DCCLIX", 759)]
    #[test_case("DCCXCII", 792)]
    #[test_case("DCCXXVII", 727)]
    #[test_case("DCCLX", 760)]
    #[test_case("DCCXCIII", 793)]
    #[test_case("DCCXXVIII", 728)]
    #[test_case("DCCLXI", 761)]
    #[test_case("DCCXCIV", 794)]
    #[test_case("DCCXXIX", 729)]
    #[test_case("DCCLXII", 762)]
    #[test_case("DCCXCV", 795)]
    #[test_case("DCCXXX", 730)]
    #[test_case("DCCLXIII", 763)]
    #[test_case("DCCXCVI", 796)]
    #[test_case("DCCXXXI", 731)]
    #[test_case("DCCLXIV", 764)]
    #[test_case("DCCXCVII", 797)]
    #[test_case("DCCXXXII", 732)]
    #[test_case("DCCLXV", 765)]
    #[test_case("DCCXCVIII", 798)]
    #[test_case("DCCXXXIII", 733)]
    #[test_case("DCCLXVI", 766)]
    #[test_case("DCCXCIX", 799)]
    #[test_case("DCCC", 800)]
    #[test_case("DCCCI", 801)]
    #[test_case("DCCCXXXIV", 834)]
    #[test_case("DCCCLXVII", 867)]
    #[test_case("DCCCII", 802)]
    #[test_case("DCCCXXXV", 835)]
    #[test_case("DCCCLXVIII", 868)]
    #[test_case("DCCCIII", 803)]
    #[test_case("DCCCXXXVI", 836)]
    #[test_case("DCCCLXIX", 869)]
    #[test_case("DCCCIV", 804)]
    #[test_case("DCCCXXXVII", 837)]
    #[test_case("DCCCLXX", 870)]
    #[test_case("DCCCV", 805)]
    #[test_case("DCCCXXXVIII", 838)]
    #[test_case("DCCCLXXI", 871)]
    #[test_case("DCCCVI", 806)]
    #[test_case("DCCCXXXIX", 839)]
    #[test_case("DCCCLXXII", 872)]
    #[test_case("DCCCVII", 807)]
    #[test_case("DCCCXL", 840)]
    #[test_case("DCCCLXXIII", 873)]
    #[test_case("DCCCVIII", 808)]
    #[test_case("DCCCXLI", 841)]
    #[test_case("DCCCLXXIV", 874)]
    #[test_case("DCCCIX", 809)]
    #[test_case("DCCCXLII", 842)]
    #[test_case("DCCCLXXV", 875)]
    #[test_case("DCCCX", 810)]
    #[test_case("DCCCXLIII", 843)]
    #[test_case("DCCCLXXVI", 876)]
    #[test_case("DCCCXI", 811)]
    #[test_case("DCCCXLIV", 844)]
    #[test_case("DCCCLXXVII", 877)]
    #[test_case("DCCCXII", 812)]
    #[test_case("DCCCXLV", 845)]
    #[test_case("DCCCLXXVIII", 878)]
    #[test_case("DCCCXIII", 813)]
    #[test_case("DCCCXLVI", 846)]
    #[test_case("DCCCLXXIX", 879)]
    #[test_case("DCCCXIV", 814)]
    #[test_case("DCCCXLVII", 847)]
    #[test_case("DCCCLXXX", 880)]
    #[test_case("DCCCXV", 815)]
    #[test_case("DCCCXLVIII", 848)]
    #[test_case("DCCCLXXXI", 881)]
    #[test_case("DCCCXVI", 816)]
    #[test_case("DCCCXLIX", 849)]
    #[test_case("DCCCLXXXII", 882)]
    #[test_case("DCCCXVII", 817)]
    #[test_case("DCCCL", 850)]
    #[test_case("DCCCLXXXIII", 883)]
    #[test_case("DCCCXVIII", 818)]
    #[test_case("DCCCLI", 851)]
    #[test_case("DCCCLXXXIV", 884)]
    #[test_case("DCCCXIX", 819)]
    #[test_case("DCCCLII", 852)]
    #[test_case("DCCCLXXXV", 885)]
    #[test_case("DCCCXX", 820)]
    #[test_case("DCCCLIII", 853)]
    #[test_case("DCCCLXXXVI", 886)]
    #[test_case("DCCCXXI", 821)]
    #[test_case("DCCCLIV", 854)]
    #[test_case("DCCCLXXXVII", 887)]
    #[test_case("DCCCXXII", 822)]
    #[test_case("DCCCLV", 855)]
    #[test_case("DCCCLXXXVIII", 888)]
    #[test_case("DCCCXXIII", 823)]
    #[test_case("DCCCLVI", 856)]
    #[test_case("DCCCLXXXIX", 889)]
    #[test_case("DCCCXXIV", 824)]
    #[test_case("DCCCLVII", 857)]
    #[test_case("DCCCXC", 890)]
    #[test_case("DCCCXXV", 825)]
    #[test_case("DCCCLVIII", 858)]
    #[test_case("DCCCXCI", 891)]
    #[test_case("DCCCXXVI", 826)]
    #[test_case("DCCCLIX", 859)]
    #[test_case("DCCCXCII", 892)]
    #[test_case("DCCCXXVII", 827)]
    #[test_case("DCCCLX", 860)]
    #[test_case("DCCCXCIII", 893)]
    #[test_case("DCCCXXVIII", 828)]
    #[test_case("DCCCLXI", 861)]
    #[test_case("DCCCXCIV", 894)]
    #[test_case("DCCCXXIX", 829)]
    #[test_case("DCCCLXII", 862)]
    #[test_case("DCCCXCV", 895)]
    #[test_case("DCCCXXX", 830)]
    #[test_case("DCCCLXIII", 863)]
    #[test_case("DCCCXCVI", 896)]
    #[test_case("DCCCXXXI", 831)]
    #[test_case("DCCCLXIV", 864)]
    #[test_case("DCCCXCVII", 897)]
    #[test_case("DCCCXXXII", 832)]
    #[test_case("DCCCLXV", 865)]
    #[test_case("DCCCXCVIII", 898)]
    #[test_case("DCCCXXXIII", 833)]
    #[test_case("DCCCLXVI", 866)]
    #[test_case("DCCCXCIX", 899)]
    #[test_case("CM", 900)]
    #[test_case("CMI", 901)]
    #[test_case("CMXXXIV", 934)]
    #[test_case("CMLXVII", 967)]
    #[test_case("CMII", 902)]
    #[test_case("CMXXXV", 935)]
    #[test_case("CMLXVIII", 968)]
    #[test_case("CMIII", 903)]
    #[test_case("CMXXXVI", 936)]
    #[test_case("CMLXIX", 969)]
    #[test_case("CMIV", 904)]
    #[test_case("CMXXXVII", 937)]
    #[test_case("CMLXX", 970)]
    #[test_case("CMV", 905)]
    #[test_case("CMXXXVIII", 938)]
    #[test_case("CMLXXI", 971)]
    #[test_case("CMVI", 906)]
    #[test_case("CMXXXIX", 939)]
    #[test_case("CMLXXII", 972)]
    #[test_case("CMVII", 907)]
    #[test_case("CMXL", 940)]
    #[test_case("CMLXXIII", 973)]
    #[test_case("CMVIII", 908)]
    #[test_case("CMXLI", 941)]
    #[test_case("CMLXXIV", 974)]
    #[test_case("CMIX", 909)]
    #[test_case("CMXLII", 942)]
    #[test_case("CMLXXV", 975)]
    #[test_case("CMX", 910)]
    #[test_case("CMXLIII", 943)]
    #[test_case("CMLXXVI", 976)]
    #[test_case("CMXI", 911)]
    #[test_case("CMXLIV", 944)]
    #[test_case("CMLXXVII", 977)]
    #[test_case("CMXII", 912)]
    #[test_case("CMXLV", 945)]
    #[test_case("CMLXXVIII", 978)]
    #[test_case("CMXIII", 913)]
    #[test_case("CMXLVI", 946)]
    #[test_case("CMLXXIX", 979)]
    #[test_case("CMXIV", 914)]
    #[test_case("CMXLVII", 947)]
    #[test_case("CMLXXX", 980)]
    #[test_case("CMXV", 915)]
    #[test_case("CMXLVIII", 948)]
    #[test_case("CMLXXXI", 981)]
    #[test_case("CMXVI", 916)]
    #[test_case("CMXLIX", 949)]
    #[test_case("CMLXXXII", 982)]
    #[test_case("CMXVII", 917)]
    #[test_case("CML", 950)]
    #[test_case("CMLXXXIII", 983)]
    #[test_case("CMXVIII", 918)]
    #[test_case("CMLI", 951)]
    #[test_case("CMLXXXIV", 984)]
    #[test_case("CMXIX", 919)]
    #[test_case("CMLII", 952)]
    #[test_case("CMLXXXV", 985)]
    #[test_case("CMXX", 920)]
    #[test_case("CMLIII", 953)]
    #[test_case("CMLXXXVI", 986)]
    #[test_case("CMXXI", 921)]
    #[test_case("CMLIV", 954)]
    #[test_case("CMLXXXVII", 987)]
    #[test_case("CMXXII", 922)]
    #[test_case("CMLV", 955)]
    #[test_case("CMLXXXVIII", 988)]
    #[test_case("CMXXIII", 923)]
    #[test_case("CMLVI", 956)]
    #[test_case("CMLXXXIX", 989)]
    #[test_case("CMXXIV", 924)]
    #[test_case("CMLVII", 957)]
    #[test_case("CMXC", 990)]
    #[test_case("CMXXV", 925)]
    #[test_case("CMLVIII", 958)]
    #[test_case("CMXCI", 991)]
    #[test_case("CMXXVI", 926)]
    #[test_case("CMLIX", 959)]
    #[test_case("CMXCII", 992)]
    #[test_case("CMXXVII", 927)]
    #[test_case("CMLX", 960)]
    #[test_case("CMXCIII", 993)]
    #[test_case("CMXXVIII", 928)]
    #[test_case("CMLXI", 961)]
    #[test_case("CMXCIV", 994)]
    #[test_case("CMXXIX", 929)]
    #[test_case("CMLXII", 962)]
    #[test_case("CMXCV", 995)]
    #[test_case("CMXXX", 930)]
    #[test_case("CMLXIII", 963)]
    #[test_case("CMXCVI", 996)]
    #[test_case("CMXXXI", 931)]
    #[test_case("CMLXIV", 964)]
    #[test_case("CMXCVII", 997)]
    #[test_case("CMXXXII", 932)]
    #[test_case("CMLXV", 965)]
    #[test_case("CMXCVIII", 998)]
    #[test_case("CMXXXIII", 933)]
    #[test_case("CMLXVI", 966)]
    #[test_case("CMXCIX", 999)]
    #[test_case("M", 1000)]

    fn try_roman_to_arab(roman: &str, expected: u32) {
        assert_eq!(crate::roman_to_arab(roman).unwrap(), expected)
    }
}
